#is:
#  build: ./sp-wso2es-is
#  ports:
#       - "9443:9443"

#espub1:
#  build: ./sp-wso2es210
#  ports:
#       - "9448:9448"
#  links:
#       - is

db:
   build: sp-mysql
   container_name: db
   environment: 
             MYSQL_ROOT_PASSWORD: root
   ports:
        - "3306:3306"

nginx:
   build: nginx
   container_name: nginx
   ports:
        - "80:80"
        - "443:443"
   links:
        - es_pub1
        - es_pub2

is:
  build: is
  container_name: is
  ports:
      - "9443"

es_pub1:
   build: publisher
   environment:
            WSO2_LOCAL_MEMBER_HOST: es_pub1
            WSO2_LOCAL_MEMBER_PORT: 4000
            WSO2_WK_MEMBER_HOST: es_pub2
            WSO2_WK_MEMBER_PORT: 4254
            WSO2_CARBON_HOST: publisher.es-wso2.com
   container_name: es_pub1
   ports:
       - "9443"
       - "4254"
       - "4000"
   links:
      - db
      - is

es_pub2:
   build: publisher
   environment:
            WSO2_LOCAL_MEMBER_HOST: es_pub2
            WSO2_LOCAL_MEMBER_PORT: 4000
            WSO2_WK_MEMBER_HOST: es_pub1
            WSO2_WK_MEMBER_PORT: 4254
            WSO2_CARBON_HOST: publisher.es-wso2.com
   container_name: es_pub2
   ports:
       - "9443"
       - "4254"
       - "4000"
   links:
      - db
      - es_pub1
      - is