#is:
#  build: ./sp-wso2es-is
#  ports:
#       - "9443:9443"

#espub1:
#  build: ./sp-wso2es210
#  ports:
#       - "9448:9448"
#  links:
#       - is

db:
   build: sp-mysql
   environment: 
             MYSQL_ROOT_PASSWORD: root
   ports:
        - "3306:3306"

pub1:
   build: publisher
   environment:
            WSO2_LOCAL_MEMBER_HOST: pub1
            WSO2_LOCAL_MEMBER_PORT: 4000
            WSO2_WK_MEMBER_HOST: pub1
            WSO2_CARBON_HOST: publisher.es-wso2.com
   container_name: pub1
   ports:
       - "9443"
   links:
      - db
