#is:
#  build: ./sp-wso2es-is
#  ports:
#       - "9443:9443"

#espub1:
#  build: ./sp-wso2es210
#  ports:
#       - "9448:9448"
#  links:
#       - is

db:
   build: sp-mysql
   environment: 
             MYSQL_ROOT_PASSWORD: root
   ports:
        - "3306:3306"

pub1:
   build: publisher
   ports:
       - "9443"
   links:
      - db
